---
title: "DSRT Notebook"
output: html_notebook
---

R Notebook for displaying the DSRT Screen data and relevant analysis. 

Import the neccesary functions:
```{r}
source("Utilities/Utility_package.R")
source("Scripts/Drug_Synergy_Package.R")
```


Import the data:

```{r}
growth_effect_matrix = import_plate_range("Sample_Data/Sample_Excel_Template.xlsx", "N10:X16")
```


Print Heatmap Scaled:
```{r}
print_heatmap_bliss_scaled(growth_effect_matrix, export_name = "Sample_Output/Sample_Output_Scaled_Heatmap.jpg", xlabel = "Drug A", ylabel = "Drug B")
```

Print Heatmap Outlier:
```{r}
print_heatmap_bliss_outlier_elim(growth_effect_matrix, 
                                 export_name = "Sample_Output/Sample_Output_Outlier_Heatmap.jpg", 
                                 xlabel = "Drug A", ylabel = "Drug B")
```

Pipeline Print Heatmap:
Here we will show how to Analyze all the XLSX files in a single folder using the Pipeline utility.
This version analyzes the files sequentially on one CPU

```{r}
input_directory = toString(paste(getwd(),"/Sample_Data",sep = ""))
output_directory = toString(paste(getwd(),"/Sample_Pipeline_Output",sep = ""))
pipeline(pipelined_print_heatmap_growth_scaled,
         input_directory, 
         output_directory,
         additional_args = ("N10:X16")) 
```